title: CPT-363
metadata:
    description: 'A short description of your course would go here'
menu:                     # menu entry for adding external sites/tools
    - text: Grav
      icon: arrow-circle-right
      url: http://getgrav.org/
icon:                     # default font awesome icons for preparation and post entries
    preparations: check-circle
    posts: calendar-o
github:
    location: page         # menu | page | none
    tree: https://github.com/hibbitts-design/grav-skeleton-bones-vanilla-course-companion-prototype/edit/master/user/
rssbutton:
    display: true
# The below are required settings for the base theme, and should not be modified
blog:
  route: ''
